<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <form class="form-horizontal" method="post" action="/forgot-password">
            <input type="hidden" name="csrf-token" value="<?= $this->escape(base64_encode($this->csrfToken->get())); ?>">
            <fieldset>
                <legend><?= $this->translate('forgot-password.form.title'); ?></legend>
                <?php $this->formBuilder->render($this->form, 'forgot-password.form.field'); ?>
                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                        <button type="submit" class="btn btn-primary"><?= $this->translate('forgot-password.form.field.submit'); ?></button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>
