<h2>Maintenance</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dui metus...</p>
<ul class="nav nav-tabs">
    <li class="active"><a href="#summary" data-toggle="tab">Status</a></li>
    <li><a href="#issues" data-toggle="tab">Queue</a></li>
</ul>
<div class="row">
    <div class="col-lg-12">
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="summary">
                <h5>Project got <em>worse</em> <span class="pull-right">5 minutes ago</span></h5>
                <table class="table summary">
                    <tbody>
                        <tr>
                            <td><i class="fa fa-warning"></i></td>
                            <td>Inspection partially failed</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-paperclip"></td>
                            <td>Added 10 new files</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-line-chart"></td>
                            <td>Code coverage <em>decreased</em> with 10%. Total coverage 26%.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="tab-pane fade" id="issues">
                <p>Here a table of files with issues will be displayed. E.g. dead code, missing doc blocks etc</p>
            </div>
            <div class="tab-pane fade" id="code">
                <p>A table of all the files will be displayed here including the grade e.g. C or A.</p>
            </div>
            <div class="tab-pane fade" id="patches">
                <p>Some issues can automagically be resolved using this project. The diffs of the patch will be disaplyed here.</p>
            </div>
            <div class="tab-pane fade" id="log">
                <p>Note: this only contains the output of PHP Unit, but other tools that ran will also have output and should also be displayed somewhere in here somehow.</p>
                <?= $this->render('/task/phpunit-log.phtml'); ?>
            </div>
        </div>
    </div>
</div>
