<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('page.not-found.title'); ?></h3>
            </div>
            <div class="panel-body">
                <?= $this->translate('page.not-found.description'); ?>
            </div>
        <div>
    </div>
    <div class="col-lg-3"></div>
<div class="row">
