<p>Some nice way to go to the <a href="/settings/projects/add">new project page</a>.</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Location</th>
            <th>Last run</th>
            <th>Grade</th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td><a href="/projects/1/test-project">Test project</a></td>
                <td>FTP</td>
                <td>ftp.pieterhordijk.com:/srv/www/Testproject</td>
                <td>Never</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td><a href="/projects/2/examinr">Examinr</a></td>
                <td>GitHub</td>
                <td>PeeHaa/examinr</td>
                <td>33 seconds ago</td>
                <td>A</td>
            </tr>
            <tr>
                <td><a href="/projects/3/examinr-local">Examinr (local)</a></td>
                <td>Local</td>
                <td>/var/www/Examinr</td>
                <td>1 minute ago</td>
                <td>B</td>
            </tr>
    </tbody>
</table>
