<div class="row header">
    <div class="col-lg-12">
        <div class="bs-component">
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <?php if (!isset($this->barePage)) { ?>
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                                <span class="sr-only"><?= $this->translate('navigation.mobile.toggle'); ?></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        <?php } ?>
                        <a class="navbar-brand" href="/"><?= $this->translate('site.name'); ?></a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                        <?php if (!isset($this->barePage)) { ?>
                            <ul class="nav navbar-nav">
                                <li <?php if ($this->request->matches('/')) echo 'class="active"'; ?>><a href="/"><?= $this->translate('navigation.item.tasks'); ?> <span class="sr-only"><?= $this->translate('navigation.current'); ?></span></a></li>
                                <li><a href="/projects"><?= $this->translate('navigation.item.projects'); ?></a></li>
                                <li class="dropdown <?php if ($this->request->startsWith('/settings')) echo 'active'; ?>">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><?= $this->translate('navigation.item.settings'); ?> <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#"><?= $this->translate('navigation.item.settings.add-project'); ?></a></li>
                                        <li><a href="#"><?= $this->translate('navigation.item.settings.users'); ?></a></li>
                                        <li><a href="#"><?= $this->translate('navigation.item.settings.maintenance'); ?></a></li>
                                        <li class="divider"></li>
                                        <li <?php if ($this->request->matches('/settings/user-info')) echo 'class="active"'; ?>><a href="/settings/user-info"><?= $this->translate('navigation.item.settings.userinfo'); ?></a></li>
                                        <li class="divider"></li>
                                        <li>
                                            <form action="/logout" method="post">
                                                <input type="hidden" name="csrf-token" value="<?= $this->escape(base64_encode($this->csrfToken->get())); ?>">
                                                <input type="submit" name="submit" value="<?= $this->translate('navigation.item.settings.logout'); ?>" class="logout">
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                </div>
                                <button type="submit" class="btn btn-default">Submit</button>
                            </form>
                        <?php } ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="https://github.com/PeeHaa/examinr" target="_blank"><span class="fa fa-github"></span></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
