<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Repository</th>
            <th>User</th>
            <th>Commit</th>
            <th>Message</th>
            <th>Success</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><a href="/repos/1/awesome-repo">User/awesome-repo</a></td>
            <td>Intern 1</td>
            <td><a href="/result/dfs86s4008589d67711798a503002f786d8f8929">dfs86s4</a></td>
            <td>I dun goofed durrrrr</td>
            <td><span class="label label-primary">Scheduled</span></td>
        </tr>
        <tr>
            <td><a href="/repos/1/awesome-repo">User/awesome-repo</a></td>
            <td>Intern 1</td>
            <td><a href="/result/880c9ef008589d67711798a503002f786d8f8929">880c9ef</a></td>
            <td>Added cached routes</td>
            <td><span class="label label-default">Running</span></td>
        </tr>
        <tr>
            <td><a href="/repos/1/awesome-repo">User/awesome-repo</a></td>
            <td>PeeHaa</td>
            <td><a href="/result/2da979dabeb4a6c405fad46f768505e5f24d8c6e">2da979d</a></td>
            <td>Fixed some fuckups</td>
            <td><span class="label label-danger">Errors</span></td>
        </tr>
        <tr>
            <td><a href="/repos/2/foobar">Organisation/foobar</a></td>
            <td>PeeHaa</td>
            <td><a href="/result/adac04cb2424cf934e32da48dd9f1894b079fd72">adac04c</a></td>
            <td>Implemented logged out pages</td>
            <td><span class="label label-success">No problems</span></td>
        </tr>
        <tr>
            <td><a href="/repos/1/awesome-repo">User/awesome-repo</a></td>
            <td>PeeHaa</td>
            <td><a href="/result/a3792c4dcff41acdcb6d43651e5efeb0c449ecce">a3792c4</a></td>
            <td>Added fields</td>
            <td><span class="label label-warning">Problems</span></td>
        </tr>
        <tr>
            <td><a href="/repos/2/foobar">Organisation/foobar</a></td>
            <td>PeeHaa</td>
            <td><a href="/result/7811bcdca9cf03e9618179d351914812b33261e0">7811bcd</a></td>
            <td>This is a longer commit message lorem ipsum dolor </td>
            <td><span class="label label-warning">Problems</span></td>
        </tr>
        <tr>
            <td><a href="/repos/2/foobar">Organisation/foobar</a></td>
            <td>Some long Username</td>
            <td><a href="/result/0b585f1c9567358062b4e0f6300e363e7360d1a4">0b585f1</a></td>
            <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dui metus...</td>
            <td><span class="label label-success">No problems</span></td>
        </tr>
    </tbody>
</table>