<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Examinr</title>
        <link rel='shortcut icon' type='image/x-icon' href='/insert-some-awesome-favicon-here.ico'>
        <link rel="stylesheet" type="text/css" href="/css/styles.css">
    </head>
    <body>
        <?= $this->render('/blocks/header.phtml'); ?>
        <?= $content; ?>
        <script src="/js/jquery-1.11.2.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/main.js"></script>
    </body>
</html>
