<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Examinr</title>
        <link rel='shortcut icon' type='image/x-icon' href='/insert-some-awesome-favicon-here.ico'>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="/css/styles.css">
    </head>
    <body>
        <?= $this->render('/blocks/header.phtml'); ?>
        <div class="container">
            <?= $content; ?>
        </div>
        <script src="/js/jquery-1.11.2.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/jquery.floatThead.min.js"></script>
        <script src="/js/main.js"></script>
    </body>
</html>
